// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUT_M2jWn4LcGwq0Cr1cKdhlEqcdZ5S90',
    appId: '1:720078137851:web:7d6f249ea85be8d805435e',
    messagingSenderId: '720078137851',
    projectId: 'songbookapp7',
    authDomain: 'songbookapp7.firebaseapp.com',
    storageBucket: 'songbookapp7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2ukdKfsHAPZjJ9ZlJZuodW6xR9yEGF6I',
    appId: '1:720078137851:android:755d7a5496786ce405435e',
    messagingSenderId: '720078137851',
    projectId: 'songbookapp7',
    storageBucket: 'songbookapp7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-MVRLeb0YXhtkHNPGg_TxFhiduHoZjC0',
    appId: '1:720078137851:ios:7071d9ca00365d4c05435e',
    messagingSenderId: '720078137851',
    projectId: 'songbookapp7',
    storageBucket: 'songbookapp7.appspot.com',
    iosBundleId: 'com.example.songbookapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-MVRLeb0YXhtkHNPGg_TxFhiduHoZjC0',
    appId: '1:720078137851:ios:7071d9ca00365d4c05435e',
    messagingSenderId: '720078137851',
    projectId: 'songbookapp7',
    storageBucket: 'songbookapp7.appspot.com',
    iosBundleId: 'com.example.songbookapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUT_M2jWn4LcGwq0Cr1cKdhlEqcdZ5S90',
    appId: '1:720078137851:web:c443b7eef3cde52905435e',
    messagingSenderId: '720078137851',
    projectId: 'songbookapp7',
    authDomain: 'songbookapp7.firebaseapp.com',
    storageBucket: 'songbookapp7.appspot.com',
  );
}
