# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting performance.
# Disable these by uncommenting the next line.
# use_frameworks!

# The target for your Flutter app
target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

# Add other pods below
